// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS7drOGCNeSe0Kn5bQWB7FyopItmpqM-Q',
    appId: '1:995915104731:web:cdf3bfdc5000183688e7fe',
    messagingSenderId: '995915104731',
    projectId: 'mynotesapp-e8934',
    authDomain: 'mynotesapp-e8934.firebaseapp.com',
    storageBucket: 'mynotesapp-e8934.firebasestorage.app',
    measurementId: 'G-NBVM63FSNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX6xPDAxWK3WOp8MF-F5MoAjQw9aDSEWY',
    appId: '1:995915104731:android:c25b05c64bdaae7e88e7fe',
    messagingSenderId: '995915104731',
    projectId: 'mynotesapp-e8934',
    storageBucket: 'mynotesapp-e8934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmIoyFnj2H4Ycn7zUnrqhwHRFQwcs7t1k',
    appId: '1:995915104731:ios:4bed67c431c42ffd88e7fe',
    messagingSenderId: '995915104731',
    projectId: 'mynotesapp-e8934',
    storageBucket: 'mynotesapp-e8934.firebasestorage.app',
    iosBundleId: 'com.example.mynotesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS7drOGCNeSe0Kn5bQWB7FyopItmpqM-Q',
    appId: '1:995915104731:web:3d00941e4b34ae4388e7fe',
    messagingSenderId: '995915104731',
    projectId: 'mynotesapp-e8934',
    authDomain: 'mynotesapp-e8934.firebaseapp.com',
    storageBucket: 'mynotesapp-e8934.firebasestorage.app',
    measurementId: 'G-4KBZY5GZZR',
  );

}